//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamAwesome1._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Labor
    {
        public int LaborNo { get; set; }
        public string EmpID { get; set; }
        public string PartNo { get; set; }
        public string OrderNo { get; set; }
        public int Hours { get; set; }
        public int Mins { get; set; }
    
        public virtual User User { get; set; }
        public virtual Part Part { get; set; }
    }
}
