//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamAwesome1._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int AutoNumber { get; set; }
        public string OrderNo { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string Die { get; set; }
        public int MachNo { get; set; }
        public int Std { get; set; }
        public string Act { get; set; }
        public Nullable<int> OnHrs { get; set; }
        public Nullable<int> Shift { get; set; }
        public string PartNo { get; set; }
        public string BoxCode { get; set; }
        public int PackerNo { get; set; }
    
        public virtual Box Box { get; set; }
        public virtual Packer Packer { get; set; }
        public virtual Part Part { get; set; }
    }
}
